/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.reto3.vista;

import com.reto3.modelo.BaseDatosProductos;
import com.reto3.modelo.Producto;
import javax.swing.JOptionPane;

/**
 *
 * @author David Serna
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Instanciar la base de datos inmediatamente se inicia el frame
     */
    private static BaseDatosProductos baseDatos = new BaseDatosProductos();

    /**
     * Necesitamos este método para acceder en cualquier momento
     *
     * @return La base de datos
     */
    public static BaseDatosProductos getBaseDatos() {
        return baseDatos;
    }

    /**
     * Genera el resumen del inventario
     */
    public static void generarInforme() {
        TablaResumenInventario ventanaResumen = new TablaResumenInventario();
        ventanaResumen.setVisible(true);
        ventanaResumen.setLocationRelativeTo(null);
    }

    /**
     * Creates new form AppPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MensajeBienvenida = new javax.swing.JLabel();
        PanelIntro = new javax.swing.JPanel();
        MensajeIntro = new javax.swing.JLabel();
        MensajeApp = new javax.swing.JLabel();
        PanelResumen = new javax.swing.JPanel();
        btnResumenMT = new javax.swing.JButton();
        btnResumenInvent = new javax.swing.JButton();
        PanelOpciones = new javax.swing.JPanel();
        MensajeOpcion = new javax.swing.JLabel();
        PanelCampos = new javax.swing.JPanel();
        labelCodigo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textCodigo = new javax.swing.JTextField();
        textPrecio = new javax.swing.JTextField();
        textCantidad = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        PanelBotonesPrinc = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnAcercade = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MensajeBienvenida.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 36)); // NOI18N
        MensajeBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MensajeBienvenida.setText("¡Bienvenidos a la tienda de David!");

        PanelIntro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MensajeIntro.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        MensajeIntro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MensajeIntro.setText("<html>Este pequeño programa está diseñado para cumplir con los requisitos del reto 3.<br>\nA continuación tiene acceso a dos botones. <br>\nUno para generar el reporte de los 3 productos con el precio más alto<br>\ny otro para ver el estado actual del inventario de la tienda.<br><br>\n\nAl lado derecho puede seleccionar que operación desea realizar. <br>\nSí escoge “AGREGAR” tenga en cuenta que el código debe ser diferente<br>\na cualquiera del inventario. La opción de “BORRAR” requiere que el código<br>\ny el nombre coincidan con el producto, igual con la opción de “ACTUALIZAR”.\n");
        MensajeIntro.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        MensajeApp.setFont(new java.awt.Font("Copperplate Gothic Light", 3, 24)); // NOI18N
        MensajeApp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MensajeApp.setText("Introducción a la App");

        btnResumenMT.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        btnResumenMT.setText("<html><p style=\"text-align:center;\">Top 3<br>Productos más costosos</p>");
        btnResumenMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumenMTActionPerformed(evt);
            }
        });

        btnResumenInvent.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        btnResumenInvent.setText("<html><p style=\"text-align:center;\">Resumen<br>Inventario</p>");
        btnResumenInvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumenInventActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelResumenLayout = new javax.swing.GroupLayout(PanelResumen);
        PanelResumen.setLayout(PanelResumenLayout);
        PanelResumenLayout.setHorizontalGroup(
            PanelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResumenLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnResumenInvent, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnResumenMT, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelResumenLayout.setVerticalGroup(
            PanelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResumenLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(PanelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnResumenInvent)
                    .addComponent(btnResumenMT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelIntroLayout = new javax.swing.GroupLayout(PanelIntro);
        PanelIntro.setLayout(PanelIntroLayout);
        PanelIntroLayout.setHorizontalGroup(
            PanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIntroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MensajeApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelResumen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIntroLayout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(MensajeIntro, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelIntroLayout.setVerticalGroup(
            PanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIntroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MensajeApp)
                .addGap(18, 18, 18)
                .addComponent(MensajeIntro, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelResumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelOpciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MensajeOpcion.setFont(new java.awt.Font("Copperplate Gothic Light", 3, 14)); // NOI18N
        MensajeOpcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MensajeOpcion.setText("<html>ESCRIBA LA INFORMACIÓN Y<br> ESCOJA UNA OPCIÓN");

        PanelCampos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelCodigo.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        labelCodigo.setText("Código");

        labelNombre.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        labelNombre.setText("Nombre");

        labelPrecio.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        labelPrecio.setText("Precio");

        labelCantidad.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        labelCantidad.setText("Cantidad");

        btnLimpiar.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCamposLayout = new javax.swing.GroupLayout(PanelCampos);
        PanelCampos.setLayout(PanelCamposLayout);
        PanelCamposLayout.setHorizontalGroup(
            PanelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCamposLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCantidad)
                    .addComponent(labelPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelCodigo)
                        .addComponent(labelNombre)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(textNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCantidad))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCamposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        PanelCamposLayout.setVerticalGroup(
            PanelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCamposLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelCamposLayout.createSequentialGroup()
                        .addGroup(PanelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCodigo)
                            .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(PanelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNombre)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(labelPrecio))
                    .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PanelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCantidad)
                    .addComponent(textCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelBotonesPrinc.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAgregar.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        btnAgregar.setText("<html><p style=\"text-align:center;\">AGREGAR</p>");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        btnActualizar.setText("<html><p style=\"text-align:center;\">ACTUALIZAR</p>");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrar.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        btnBorrar.setText("<html><p style=\"text-align:center;\">BORRAR</p>");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnAcercade.setFont(new java.awt.Font("Copperplate Gothic Light", 2, 14)); // NOI18N
        btnAcercade.setText("<html><p style=\"text-align:center;\">© Acerca de</p>");
        btnAcercade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercadeActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reto3/vista/carritomini.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelBotonesPrincLayout = new javax.swing.GroupLayout(PanelBotonesPrinc);
        PanelBotonesPrinc.setLayout(PanelBotonesPrincLayout);
        PanelBotonesPrincLayout.setHorizontalGroup(
            PanelBotonesPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBotonesPrincLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBotonesPrincLayout.createSequentialGroup()
                .addGroup(PanelBotonesPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBotonesPrincLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAcercade, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBotonesPrincLayout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelBotonesPrincLayout.setVerticalGroup(
            PanelBotonesPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesPrincLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBotonesPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelBotonesPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBotonesPrincLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAcercade, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(PanelBotonesPrincLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout PanelOpcionesLayout = new javax.swing.GroupLayout(PanelOpciones);
        PanelOpciones.setLayout(PanelOpcionesLayout);
        PanelOpcionesLayout.setHorizontalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MensajeOpcion)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addComponent(PanelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PanelBotonesPrinc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelOpcionesLayout.setVerticalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MensajeOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelBotonesPrinc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MensajeBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelIntro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MensajeBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelIntro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     *
     * @param operacion Agregar, Borrar, Actualizar
     */
    private void realizarOperacion(String operacion) {
        if (textCodigo.getText().isEmpty() || textNombre.getText().isEmpty() || textCantidad.getText().isEmpty() || textPrecio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            String codigo = textCodigo.getText();
            String nombre = textNombre.getText();
            String precio = textPrecio.getText();
            String cantidad = textCantidad.getText();

            try {
                int codigoInt = Integer.parseInt(codigo);
                double precioDouble = Double.parseDouble(precio);
                int cantidadInt = Integer.parseInt(cantidad);

                if (codigoInt <= 0 || precioDouble <= 0 || cantidadInt <= 0) {
                    JOptionPane.showMessageDialog(this, "El código, el precio y la cantidad\n deben ser mayores que 0", "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    Producto nuevoProducto = new Producto(codigoInt, nombre, precioDouble, cantidadInt);
                    baseDatos.realizarOperacion(operacion, nuevoProducto);
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Existen campos inválidos.\n"
                        + "Recuerde que el código es un valor entero, igual que la cantidad.\n"
                        + "El precio es un número real y el nombre cualquier cadena de caracteres.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        }
    }

    /**
     *
     * @param evt Imprime un botón con el resumen solicitado por Master Tech
     */
    private void btnResumenMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumenMTActionPerformed
        JOptionPane.showMessageDialog(this, baseDatos.imprimirReporte(), "Resumen MT", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnResumenMTActionPerformed
    /**
     *
     * @param evt Imprime un botón con el inventario
     */
    private void btnResumenInventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumenInventActionPerformed
        this.generarInforme();
    }//GEN-LAST:event_btnResumenInventActionPerformed
    /**
     *
     * @param evt Actualizar el inventario con el producto escrito
     */
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        realizarOperacion("ACTUALIZAR");
    }//GEN-LAST:event_btnActualizarActionPerformed
    /**
     *
     * @param evt Agrega al inventario el producto escrito
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        realizarOperacion("AGREGAR");
    }//GEN-LAST:event_btnAgregarActionPerformed
    /**
     *
     * @param evt Borra del inventario el producto escrito
     */
    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        realizarOperacion("BORRAR");
    }//GEN-LAST:event_btnBorrarActionPerformed
    /**
     *
     * @param evt Imprime información sobre mí
     */
    private void btnAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercadeActionPerformed
        JOptionPane.showMessageDialog(this, "Mi nombre es David Serna Gutérrez.\nIngeniero Forestal, científico de datos y especializasta SIG.\n"
                + "\nEste es un programa básico para realizar compras en un supermarket.\nPor favor respete los derechos de autor.\n\n"
                + "©David Serna\ne-mail: dsernag@unal.edu.co\n\n\nGracias por compilar y correr.", "Acerca de mí", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAcercadeActionPerformed
    /**
     *
     * @param evt Limpia los campos
     */
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        textCodigo.setText("");
        textNombre.setText("");
        textPrecio.setText("");
        textCantidad.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args methow to run the frame
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MensajeApp;
    private javax.swing.JLabel MensajeBienvenida;
    private javax.swing.JLabel MensajeIntro;
    private javax.swing.JLabel MensajeOpcion;
    private javax.swing.JPanel PanelBotonesPrinc;
    private javax.swing.JPanel PanelCampos;
    private javax.swing.JPanel PanelIntro;
    private javax.swing.JPanel PanelOpciones;
    private javax.swing.JPanel PanelResumen;
    private javax.swing.JButton btnAcercade;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnResumenInvent;
    private javax.swing.JButton btnResumenMT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JTextField textCantidad;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPrecio;
    // End of variables declaration//GEN-END:variables
}
